# Use this file to configure your custom Rec Code font

# The name you want after "Rec Mono" in your custom fonts
Family Name: Custom 

# The variable axis values for the Regular, Italic, Bold, & Bold Italic fonts

# MONO: 0 for Sans, 1 for Mono (or anything in-between)
# CASL: 0 for Linear, 1 for Casual (or anything in-between)
# wght: 300â€“1000 (realistically, about 400 for Regular & Italic and about 700 for Bold & Bold Italic)
# slnt: 0 to -15 (negative numbers are more slanted, and approximately equal to degrees of slope)
# CRSV: 0 (0 for roman, 1 for cursive)

Fonts:

  Regular:
    MONO: 1
    CASL: 0
    wght: 425
    slnt: 0
    CRSV: 0

  Italic:
    MONO: 1
    CASL: 1
    wght: 425
    slnt: -10
    CRSV: 0

  Bold:
    MONO: 1
    CASL: 0
    wght: 700
    slnt: 0
    CRSV: 0

  Bold Italic:
    MONO: 1
    CASL: 1
    wght: 700
    slnt: -10
    CRSV: 1

# Freeze in code ligatures? True or False
Code Ligatures: True

# Include font features to freeze in stylistic options. Copy them below to use. See README for details.
# ss01 # single-story a
# ss02 # single-story g
# ss03 # simplified f
# ss04 # simplified i
# ss05 # simplified l
# ss06 # simplified r
# ss07 # serifless L and Z
# ss07 # serifless L and Z
# ss08 # simplified @
# ss09 # simplified 6 and 9
# ss10 # dotted 0
# ss11 # simplified 1

# (Keep the hyphen before each list item)
Features:
- ss02 # single-story g
- ss03 # simplified f
- ss05 # simplified l
- ss07 # serifless L and Z
- ss09 # simplified 6 and 9
